### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sweeezy** [bartucank/Fivem-Discord-Bot#1]
TypeError: Cannot read property 'pollRate' of undefined
at Object.<anonymous> (/app/server.js:64:12)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

**Comment by bartucank** [comment]
Hi!
Can you do the following steps in order?

1- Download the project again.
2- Delete package-lock.json
3- Open cmd and then change into the project directory
4- Initialise an NPM package (npm init)
